[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.20.1", features = ["full"] }
color-eyre = { version = "0.5", default-features = false }
dotenv = "0.15.0"
